name: Deploy demo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - demo/**
      - scripts/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - name: Build
        run: |
          pnpm i && pnpm build
          mkdir output
          node . generate --cwd demo -o output/index.html --default-open marktiddly
          echo '<script async defer data-website-id="74d7c261-0e76-42b1-8092-1ec201c687e3" src="https://u.gerald.win/u.js"></script>' >> output/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
